# Generated by Django 4.2.5 on 2023-09-09 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedback_app.countries', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='rating',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedback_app.rating', verbose_name='Оценка'),
        ),
    ]
